name: 'keywords_monitor'

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8081:81"
    volumes:
      - "./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./backend:/var/www/laravel"
    depends_on:
      - mysql
      - php

  php:
    build:
      context: "./docker/php"
      dockerfile: "Dockerfile"
    volumes:
      - "./backend:/var/www/laravel"

  mysql:
    image: mysql:8.2.0
    ports:
      - "3316:3306"
    env_file:
      - "docker/env/mysql.env"
    volumes:
      - "db_data:/var/lib/mysql"

  composer:
    image: composer:latest
    working_dir: /var/www/laravel
    volumes:
      - "./backend:/var/www/laravel"

  artisan:
    build:
      context: "./docker/php"
      dockerfile: "Dockerfile"
    volumes:
      - "./backend:/var/www/laravel"
    working_dir: /var/www/laravel
    entrypoint: [ "php", "artisan" ]
    depends_on:
      - mysql
    networks:
      - default

  frontend:
    image: node:current-alpine
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"
    ports:
      - "5174:5173"
    working_dir: /app
    command: npm run dev -- --host

  soketi:
    image: quay.io/soketi/soketi:1.0-16-alpine
    ports:
      - "6001:6001"
    environment:
      DEBUG: 1
      SOKETI_DEFAULT_APP_ID: local
      SOKETI_DEFAULT_APP_KEY: local
      SOKETI_DEFAULT_APP_SECRET: local

volumes:
  db_data: